### ISSUE TITLE
Sort Elastic Beanstalk OptionSettings

### ISSUE THREAD

**Issue by elijahchancey** [elijahchancey/pretty_cloudformation#6]
From an example Cloudformation template:
```
Resources:
  ConfigurationTemplate:
    Properties:
      ApplicationName:
        Ref: GithubRepo
      Description: 'AWS ElasticBeanstalk Configuration Template'
      OptionSettings:
      - Namespace: aws:elasticbeanstalk:application:environmentB
        OptionName: EnvironmentName
        Value: 'blah'
      - Namespace: aws:elasticbeanstalk:application:environmentA
        OptionName: Region
        Value: 'blah'
```

All of the OptionSettings should be sorted by Namespace. That is, `aws:elasticbeanstalk:application:environmentA` should come before `aws:elasticbeanstalk:application:environmentB`
